In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import logging

# Ensure logs are visible in your notebook (using force=True just in case)
logging.basicConfig(level=logging.INFO, format='%(message)s', force=True)
# 🤫 Silence the noisy external libraries and the text extraction parser
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpxthrottlecache").setLevel(logging.WARNING)
logging.getLogger("src.simple_rag.extraction.parser").setLevel(logging.WARNING)

### Vanguard Index Funds

In [ ]:
from src.simple_rag.extraction.filing_retriever import FilingRetriever
from src.simple_rag.utils.fund_utils import print_fund_info
retriever = FilingRetriever(email_identity="luis.alvarez.conde@alumnos.upm.es")
result = retriever.get_ncsr_filings("VOO", vanguard=True, verbose=True) 


funds = []  
funds.extend(result.funds)                          
  
# Run Verifier
warnings = FilingRetriever.verify_ncsr_data(result)
if not warnings:
    print("All parsed data looks perfectly clean! ✅")
else:
    print("Data issues found:")
    for ticker, issues in warnings.items():
        print(f"  {ticker}: {issues}")   
print(f"{len(funds)} funds from {result.filings_processed} filings")
print_fund_info(funds[:1])

/home/luis/Desktop/code/RAG/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Identity of the Edgar REST client set to [luis.alvarez.conde@alumnos.upm.es]
Identity of the Edgar REST client set to [luis.alvarez.conde@alumnos.upm.es]
[VOO] Processing N-CSR filing: 2025-12-31

Processing filing:  2025-12-31

Processing: Vanguard 500 Index Fund
Processing: Vanguard 500 Index Fund
Processing: Vanguard 500 Index Fund
Processing: Vanguard 500 Index Fund
Processing: Vanguard Value Index Fund
Processing: Vanguard Value Index Fund
Processing: Vanguard Value Index Fund
Processing: Vanguard Value Index Fund
Processing: Vanguard Growth Index Fund
Processing: Vanguard Growth Index Fund
Processing: Vanguard Growth Index Fund
Processing: Vanguard Growth Index Fund
Processing: Vanguard Large-Cap Index Fund
Processing: Vanguard Large-Cap Index Fund
Processing: Vanguard Large-Cap Index Fund
Processing: Vanguard Large-Cap Index Fund
[VOO] Filing 2026-02-27: 16 funds extracted
[VOO] Processing N-CSR filing: 2025-12-31

Processing: Vanguard 500 Index Fund Investor Shares
Processing: Vanguard 500 Index Fund ETF Shares
Processing: Vanguard 500 Index Fund Admiral Shares
Processing: Vanguard 500 Index Fund Institutional Select Shares
Processing: Vanguard Value Index Fund Investor Shares
Processing: Vanguard Value Index Fund ETF Shares
Processing: Vanguard Value Index Fund Admiral Shares
Processing: Vanguard Value Index Fund Institutional Shares
Processing: Vanguard Growth Index Fund Investor Shares
Processing: Vanguard Growth Index Fund ETF Shares
Processing: Vanguard Growth Index Fund Admiral Shares
Processing: Vanguard Growth Index Fund Institutional Shares
Processing: Vanguard Large-Cap Index Fund Investor Shares
Processing: Vanguard Large-Cap Index Fund ETF Shares
Processing: Vanguard Large-Cap Index Fund Admiral Shares
Processing: Vanguard Large-Cap Index Fund Institutional Shares
Processing filing:  2025-12-31

Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund

Processing: Vanguard Extended Market Index Fund Investor Shares
Processing: Vanguard Extended Market Index Fund ETF Shares
Processing: Vanguard Extended Market Index Fund Admiral Shares
Processing: Vanguard Extended Market Index Fund Institutional Shares
Processing: Vanguard Extended Market Index Fund Institutional Plus Shares
Processing: Vanguard Mid-Cap Index Fund Investor Shares
Processing: Vanguard Mid-Cap Index Fund ETF Shares
Processing: Vanguard Mid-Cap Index Fund Admiral Shares
Processing: Vanguard Mid-Cap Index Fund Institutional Shares
Processing: Vanguard Mid-Cap Index Fund Institutional Plus Shares
Processing: Vanguard Mid-Cap Growth Index Fund Investor Shares
Processing: Vanguard Mid-Cap Growth Index Fund ETF Shares
Processing: Vanguard Mid-Cap Growth Index Fund Admiral Shares
Processing: Vanguard Mid-Cap Value Index Fund Investor Shares
Processing: Vanguard Mid-Cap Value Index Fund ETF Shares
Processing: Vanguard Mid-Cap Value Index Fund Admiral Shares
Processing: Vanguard Small-Cap Index Fund Investor Shares
Processing: Vanguard Small-Cap Index Fund ETF Shares
Processing: Vanguard Small-Cap Index Fund Admiral Shares
Processing: Vanguard Small-Cap Index Fund Institutional Shares
Processing: Vanguard Small-Cap Index Fund Institutional Plus Shares
Processing: Vanguard Small-Cap Growth Index Fund Investor Shares
Processing: Vanguard Small-Cap Growth Index Fund ETF Shares
Processing: Vanguard Small-Cap Growth Index Fund Admiral Shares
Processing: Vanguard Small-Cap Growth Index Fund Institutional Shares
Processing: Vanguard Small-Cap Value Index Fund Investor Shares
Processing: Vanguard Small-Cap Value Index Fund ETF Shares
Processing: Vanguard Small-Cap Value Index Fund Admiral Shares
Processing: Vanguard Small-Cap Value Index Fund Institutional Shares
Processing: Vanguard Total Stock Market Index Fund Investor Shares
Processing: Vanguard Total Stock Market Index Fund ETF Shares
Processing: Vanguard Total Stock Market Index Fund Admiral Shares
Processing: Vanguard Total Stock Market Index Fund Institutional Shares
Processing: Vanguard Total Stock Market Index Fund Institutional Plus Shares
Processing: Vanguard Total Stock Market Index Fund Institutional Select Shares

[VOO] Filing 2026-02-27: 35 funds extracted
[VOO] Processing N-CSR filing: 2024-12-31

Processing filing:  2024-12-31

Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Extended Market Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Growth Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Mid-Cap Value Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Growth Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Small-Cap Value Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
Processing: Vanguard Total Stock Market Index Fund
[VOO] Duplicate fund ticker 'VEXMX' — stopping iteration
[VOO] N-CSR complete: 51 funds from 2 filing(s)
[VOO] Enrichment complete

Processing: Vanguard Extended Market Index Fund Investor Shares
Fund already exists:  VEXMX aborting
Number of funds with performance chart: 16
Funds extracted (51):  {'VSTSX', 'VLCAX', 'VLISX', 'VIMAX', 'VSCPX', 'VIMSX', 'VUG', 'VOE', 'VVIAX', 'VTI', 'VO', 'VMVAX', 'VV', 'VEXAX', 'VSMPX', 'VSIAX', 'VIGAX', 'VIEIX', 'VSMAX', 'VXF', 'VITSX', 'VMGMX', 'VMVIX', 'VIGIX', 'VB', 'VOO', 'VMGIX', 'VISGX', 'VBK', 'VFIAX', 'VTV', 'VFINX', 'VIVIX', 'VOT', 'VMCPX', 'VEMPX', 'VBR', 'VISVX', 'VTSAX', 'VTSMX', 'VFFSX', 'VSGIX', 'NAESX', 'VSGAX', 'VLACX', 'VSIIX', 'VIGRX', 'VEXMX', 'VSCIX', 'VMCIX', 'VIVAX'}
All parsed data looks perfectly clean! ✅
51 funds from 2 filings
Showing information of 2 funds

### 🏦 Vanguard 500 Index Fund

🆔 Context ID:      From2025-01-01to2025-12-31_C000007773Member
🎫 Ticker:          VFINX
🏷️ Share Class:     ShareClassType.INVESTOR
📅 Report Date:     2025-12-31
🏛️ Sec Exchange:    N/A
📋 Registrant:     Vanguard Index Funds

--- 💰 Costs & Financials ---
Net Assets          : 1480375000000.0
Expense Ratio       : 0.14
Turnover Rate       : 2.0
Costs per $10k      : 15
Advisory Fees       : 27060000.0
Number of Holdings  : 517

📝 Commentary: "How did the Fund perform during the reporting period? For the 12 months ended December 31, 2025, the Fund performed in line with its benchmark.The first part of the year was marked by volatility in the financial markets amid fears that U.S. tariff an..."

**📈 Performance History**

,Unnamed: 0,Investor Shares,S&P 500 Index,Dow Jones U.S. Total Stock Market Float Adjusted Index
0,2015,"$10,000","$10,000","$10,000"
1,2016,"$10,131","$10,135","$10,091"
2,2016,"$10,376","$10,384","$10,355"
3,2016,"$10,773","$10,784","$10,815"
4,2016,"$11,182","$11,196","$11,262"
5,2017,"$11,856","$11,875","$11,914"
6,2017,"$12,217","$12,242","$12,273"
7,2017,"$12,761","$12,790","$12,833"
8,2017,"$13,605","$13,640","$13,645"
9,2018,"$13,496","$13,537","$13,563"
10,2018,"$13,955","$14,002","$14,088"
11,2018,"$15,025","$15,081","$15,089"
12,2018,"$12,989","$13,042","$12,923"
13,2019,"$14,758","$14,822","$14,737"
14,2019,"$15,388","$15,460","$15,339"
15,2019,"$15,645","$15,723","$15,514"
16,2019,"$17,058","$17,149","$16,916"
17,2020,"$13,709","$13,788","$13,370"
18,2020,"$16,521","$16,620","$16,323"
19,2020,"$17,991","$18,105","$17,804"
20,2020,"$20,171","$20,304","$20,432"
21,2021,"$21,411","$21,558","$21,750"
22,2021,"$23,233","$23,401","$23,553"
23,2021,"$23,360","$23,537","$23,525"
24,2021,"$25,926","$26,132","$25,675"
25,2022,"$24,725","$24,931","$24,289"
26,2022,"$20,736","$20,916","$20,199"
27,2022,"$19,717","$19,895","$19,277"
28,2022,"$21,200","$21,399","$20,661"
29,2023,"$22,781","$23,004","$22,158"
30,2023,"$24,764","$25,015","$24,017"
31,2023,"$23,945","$24,196","$23,227"
32,2023,"$26,735","$27,025","$26,045"
33,2024,"$29,547","$29,878","$28,661"
34,2024,"$30,802","$31,157","$29,590"
35,2024,"$32,603","$32,992","$31,412"
36,2024,"$33,377","$33,786","$32,263"
37,2025,"$31,940","$32,343","$30,692"
38,2025,"$35,423","$35,882","$34,095"
39,2025,"$38,286","$38,797","$36,897"
40,2025,"$39,289","$39,827","$37,765"

**📊 Average Annual Returns**

                                          Unnamed: 0  1 Year 5 Years 10 Years
0                                    Investor Shares  17.71%  14.26%   14.66%
1                                      S&P 500 Index  17.88%  14.42%   14.82%
2  Dow Jones U.S. Total Stock Market Float Adjust...  17.05%  13.07%   14.21%

**🏗️ Sector Allocation**

                                   0      1
0             Communication Services  10.6%
1             Consumer Discretionary  10.4%
2                   Consumer Staples   4.7%
3                             Energy   2.8%
4                         Financials  13.2%
5                        Health Care   9.6%
6                        Industrials   8.2%
7             Information Technology  34.4%
8                          Materials   1.8%
9                        Real Estate   1.8%
10                         Utilities   2.3%
11  Other Assets and Liabilities—Net   0.2%

================================================================================

### 🏦 Vanguard 500 Index Fund

🆔 Context ID:      From2025-01-01to2025-12-31_C000092055Member
🎫 Ticker:          VOO
🏷️ Share Class:     ShareClassType.ETF
📅 Report Date:     2025-12-31
🏛️ Sec Exchange:    NYSE Arca
📋 Registrant:     Vanguard Index Funds

--- 💰 Costs & Financials ---
Net Assets          : 1480375000000.0
Expense Ratio       : 0.03
Turnover Rate       : 2.0
Costs per $10k      : 3
Advisory Fees       : 27060000.0
Number of Holdings  : 517

📝 Commentary: "How did the Fund perform during the reporting period? For the 12 months ended December 31, 2025, the Fund performed in line with its benchmark.The first part of the year was marked by volatility in the financial markets amid fears that U.S. tariff an..."

**📈 Performance History**

,Unnamed: 0,ETF Shares Net Asset Value,S&P 500 Index,Dow Jones U.S. Total Stock Market Float Adjusted Index
0,2015,"$10,000","$10,000","$10,000"
1,2016,"$10,134","$10,135","$10,091"
2,2016,"$10,381","$10,384","$10,355"
3,2016,"$10,781","$10,784","$10,815"
4,2016,"$11,193","$11,196","$11,262"
5,2017,"$11,870","$11,875","$11,914"
6,2017,"$12,235","$12,242","$12,273"
7,2017,"$12,783","$12,790","$12,833"
8,2017,"$13,631","$13,640","$13,645"
9,2018,"$13,525","$13,537","$13,563"
10,2018,"$13,988","$14,002","$14,088"
11,2018,"$15,065","$15,081","$15,089"
12,2018,"$13,029","$13,042","$12,923"
13,2019,"$14,806","$14,822","$14,737"
14,2019,"$15,442","$15,460","$15,339"
15,2019,"$15,705","$15,723","$15,514"
16,2019,"$17,128","$17,149","$16,916"
17,2020,"$13,766","$13,788","$13,370"
18,2020,"$16,593","$16,620","$16,323"
19,2020,"$18,074","$18,105","$17,804"
20,2020,"$20,270","$20,304","$20,432"
21,2021,"$21,521","$21,558","$21,750"
22,2021,"$23,359","$23,401","$23,553"
23,2021,"$23,492","$23,537","$23,525"
24,2021,"$26,079","$26,132","$25,675"
25,2022,"$24,876","$24,931","$24,289"
26,2022,"$20,869","$20,916","$20,199"
27,2022,"$19,847","$19,895","$19,277"
28,2022,"$21,346","$21,399","$20,661"
29,2023,"$22,943","$23,004","$22,158"
30,2023,"$24,947","$25,015","$24,017"
31,2023,"$24,128","$24,196","$23,227"
32,2023,"$26,949","$27,025","$26,045"
33,2024,"$29,791","$29,878","$28,661"
34,2024,"$31,064","$31,157","$29,590"
35,2024,"$32,890","$32,992","$31,412"
36,2024,"$33,680","$33,786","$32,263"
37,2025,"$32,239","$32,343","$30,692"
38,2025,"$35,764","$35,882","$34,095"
39,2025,"$38,666","$38,797","$36,897"
40,2025,"$39,690","$39,827","$37,765"

**📊 Average Annual Returns**

                                          Unnamed: 0  1 Year 5 Years 10 Years
0                         ETF Shares Net Asset Value  17.84%  14.38%   14.78%
1                            ETF Shares Market Price  17.82%  14.38%   14.78%
2                                      S&P 500 Index  17.88%  14.42%   14.82%
3  Dow Jones U.S. Total Stock Market Float Adjust...  17.05%  13.07%   14.21%

**🏗️ Sector Allocation**

                                   0      1
0             Communication Services  10.6%
1             Consumer Discretionary  10.4%
2                   Consumer Staples   4.7%
3                             Energy   2.8%
4                         Financials  13.2%
5                        Health Care   9.6%
6                        Industrials   8.2%
7             Information Technology  34.4%
8                          Materials   1.8%
9                        Real Estate   1.8%
10                         Utilities   2.3%
11  Other Assets and Liabilities—Net   0.2%

================================================================================

### Vanguard World Fund

In [4]:
from src.simple_rag.extraction.filing_retriever import FilingRetriever
from src.simple_rag.utils.fund_utils import print_fund_info
retriever = FilingRetriever(email_identity="luis.alvarez.conde@alumnos.upm.es")
result = retriever.get_ncsr_filings("MGK", vanguard=True, verbose=True)  


funds.extend(result.funds)                          

# Run Verifier
warnings = FilingRetriever.verify_ncsr_data(result)
if not warnings:
    print("All parsed data looks perfectly clean! ✅")
else:
    print("Data issues found:")
    for ticker, issues in warnings.items():
        print(f"  {ticker}: {issues}")   
print(f"{len(result.funds)} funds from {result.filings_processed} filings")
print_fund_info(result.funds[:2])

Identity of the Edgar REST client set to [luis.alvarez.conde@alumnos.upm.es]
[MGK] Processing N-CSR filing: 2025-09-30
Processing: Vanguard Mega Cap Growth Index Fund
Processing: Vanguard Mega Cap Growth Index Fund

Processing filing:  2025-09-30

[MGK] Filing 2025-11-28: 2 funds extracted
[MGK] Processing N-CSR filing: 2025-08-31

Processing: Vanguard Mega Cap Growth Index Fund ETF Shares
Processing: Vanguard Mega Cap Growth Index Fund Institutional Shares
Processing filing:  2025-08-31

Processing: Vanguard Extended Duration Treasury Index Fund
Processing: Vanguard Extended Duration Treasury Index Fund
Processing: Vanguard ESG U.S. Stock ETF
Processing: Vanguard ESG International Stock ETF
Processing: Vanguard Global Wellington™ Fund
Processing: Vanguard Global Wellington™ Fund
Processing: Vanguard Global Wellesley® Income Fund
Processing: Vanguard Global Wellesley® Income Fund
Processing: Vanguard ESG U.S. Corporate Bond ETF
[MGK] Filing 2025-10-29: 9 funds extracted
[MGK] Processing N-CSR filing: 2025-08-31

Processing: Vanguard Extended Duration Treasury Index Fund ETF Shares
Processing: Vanguard Extended Duration Treasury Index Fund Institutional Shares
Processing: Vanguard ESG U.S. Stock ETF ETF Shares
Processing: Vanguard ESG International Stock ETF ETF Shares
Processing: Vanguard Global Wellington™ Fund Investor Shares
Processing: Vanguard Global Wellington™ Fund Admiral Shares
Processing: Vanguard Global Wellesley® Income Fund Investor Shares
Processing: Vanguard Global Wellesley® Income Fund Admiral Shares
Processing: Vanguard ESG U.S. Corporate Bond ETF ETF Shares
Processing filing:  2025-08-31

Processing: Vanguard FTSE Social Index Fund
Processing: Vanguard FTSE Social Index Fund
Processing: Vanguard Materials Index Fund
Processing: Vanguard Materials Index Fund
Processing: Vanguard Communication Services Index Fund
Processing: Vanguard Communication Services Index Fund
Processing: Vanguard U.S. Growth Fund
Processing: Vanguard U.S. Growth Fund
Processing: Vanguard Utilities Index Fund
Processing: Vanguard Utilities Index Fund
Processing: Vanguard Consumer Discretionary Index Fund
Processing: Vanguard Consumer Discretionary Index Fund
Processing: Vanguard Consumer Staples Index Fund
Processing: Vanguard Consumer Staples Index Fund
Processing: Vanguard Energy Index Fund
Processing: Vanguard Energy Index Fund
Processing: Vanguard Financials Index Fund
Processing: Vanguard Financials Index Fund
Processing: Vanguard Health Care Index Fund
Processing: Vanguard Health Care Index Fund
Processing: Vanguard Industrials Index Fund
Processing: Vanguard Industrials Index Fund
Processing: Vanguard Information Technology Index Fund
Processing: Vanguard Information Technology Index Fund
Processing: Vanguard International Growth Fund
Processing: Vanguard International Growth Fund
Processing: Vanguard Mega Cap Index Fund
Processing: Vanguard Mega Cap Index Fund
Processing: Vanguard Mega Cap Value Index Fund
Processing: Vanguard Mega Cap Value Index Fund
[MGK] Filing 2025-10-29: 30 funds extracted
[MGK] Processing N-CSR filing: 2024-09-30

Processing: Vanguard FTSE Social Index Fund Admiral Shares
Processing: Vanguard FTSE Social Index Fund Institutional Shares
Processing: Vanguard Materials Index Fund ETF Shares
Processing: Vanguard Materials Index Fund Admiral Shares
Processing: Vanguard Communication Services Index Fund ETF Shares
Processing: Vanguard Communication Services Index Fund Admiral Shares
Processing: Vanguard U.S. Growth Fund Investor Shares
Processing: Vanguard U.S. Growth Fund Admiral Shares
Processing: Vanguard Utilities Index Fund ETF Shares
Processing: Vanguard Utilities Index Fund Admiral Shares
Processing: Vanguard Consumer Discretionary Index Fund ETF Shares
Processing: Vanguard Consumer Discretionary Index Fund Admiral Shares
Processing: Vanguard Consumer Staples Index Fund ETF Shares
Processing: Vanguard Consumer Staples Index Fund Admiral Shares
Processing: Vanguard Energy Index Fund ETF Shares
Processing: Vanguard Energy Index Fund Admiral Shares
Processing: Vanguard Financials Index Fund ETF Shares
Processing: Vanguard Financials Index Fund Admiral Shares
Processing: Vanguard Health Care Index Fund ETF Shares
Processing: Vanguard Health Care Index Fund Admiral Shares
Processing: Vanguard Industrials Index Fund ETF Shares
Processing: Vanguard Industrials Index Fund Admiral Shares
Processing: Vanguard Information Technology Index Fund ETF Shares
Processing: Vanguard Information Technology Index Fund Admiral Shares
Processing: Vanguard International Growth Fund Investor Shares
Processing: Vanguard International Growth Fund Admiral Shares
Processing: Vanguard Mega Cap Index Fund ETF Shares
Processing: Vanguard Mega Cap Index Fund Institutional Shares
Processing: Vanguard Mega Cap Value Index Fund ETF Shares
Processing: Vanguard Mega Cap Value Index Fund Institutional Shares
Processing filing:  2024-09-30

Processing: Vanguard Mega Cap Growth Index Fund
Processing: Vanguard Mega Cap Growth Index Fund
[MGK] Duplicate fund ticker 'MGK' — stopping iteration
[MGK] N-CSR complete: 41 funds from 3 filing(s)
[MGK] Enrichment complete

Processing: Vanguard Mega Cap Growth Index Fund ETF Shares
Fund already exists:  MGK aborting
Number of funds with performance chart: 32
Funds extracted (41):  {'VOX', 'VMCTX', 'VGWAX', 'VFTAX', 'VSGX', 'VIS', 'VHT', 'VGT', 'VGWLX', 'VFH', 'VEDTX', 'VAW', 'VINAX', 'VUIAX', 'EDV', 'VFAIX', 'VGYAX', 'VPU', 'VWUAX', 'VCDAX', 'MGC', 'VMVLX', 'VMIAX', 'VHCIX', 'VGWIX', 'VMGAX', 'VWIGX', 'VDC', 'VTCAX', 'VDE', 'ESGV', 'VCEB', 'VWILX', 'VITAX', 'MGV', 'VFTNX', 'VCR', 'VCSAX', 'VWUSX', 'MGK', 'VENAX'}
All parsed data looks perfectly clean! ✅
41 funds from 3 filings
Showing information of 2 funds

### 🏦 Vanguard Mega Cap Growth Index Fund

🆔 Context ID:      From2024-10-01to2025-09-30_C000055216Member
🎫 Ticker:          MGK
🏷️ Share Class:     ShareClassType.ETF
📅 Report Date:     2025-09-30
🏛️ Sec Exchange:    NYSE Arca
📋 Registrant:     Vanguard World Fund

--- 💰 Costs & Financials ---
Net Assets          : 31303000000.0
Expense Ratio       : 0.07
Turnover Rate       : 14.0
Costs per $10k      : 8
Advisory Fees       : 551000.0
Number of Holdings  : 69

📝 Commentary: "How did the Fund perform during the reporting period? For the 12 months ended September 30, 2025, the Fund performed in line with its benchmark.Optimism in the U.S. about deregulation, tax cuts, and artificial intelligence was occasionally tempered b..."

**📈 Performance History**

,Unnamed: 0,ETF Shares Net Asset Value,CRSP US Mega Cap Growth Index,Dow Jones U.S. Total Stock Market Float Adjusted Index
0,2015,"$10,000","$10,000","$10,000"
1,2015,"$10,724","$10,724","$10,627"
2,2016,"$10,764","$10,767","$10,724"
3,2016,"$10,848","$10,852","$11,005"
4,2016,"$11,418","$11,424","$11,493"
5,2016,"$11,409","$11,416","$11,968"
6,2017,"$12,578","$12,588","$12,661"
7,2017,"$13,191","$13,205","$13,042"
8,2017,"$13,860","$13,876","$13,638"
9,2017,"$14,772","$14,791","$14,501"
10,2018,"$14,943","$14,963","$14,413"
11,2018,"$15,899","$15,923","$14,971"
12,2018,"$17,177","$17,204","$16,035"
13,2018,"$14,349","$14,370","$13,733"
14,2019,"$16,699","$16,725","$15,661"
15,2019,"$17,446","$17,477","$16,301"
16,2019,"$17,869","$17,903","$16,487"
17,2019,"$19,736","$19,776","$17,976"
18,2020,"$17,261","$17,302","$14,208"
19,2020,"$22,232","$22,287","$17,347"
20,2020,"$25,295","$25,361","$18,921"
21,2020,"$27,826","$27,902","$21,714"
22,2021,"$28,256","$28,340","$23,114"
23,2021,"$31,650","$31,748","$25,030"
24,2021,"$32,170","$32,275","$25,000"
25,2021,"$35,753","$35,875","$27,285"
26,2022,"$32,243","$32,358","$25,812"
27,2022,"$24,976","$25,068","$21,466"
28,2022,"$23,996","$24,089","$20,486"
29,2022,"$23,755","$23,850","$21,956"
30,2023,"$28,269","$28,387","$23,547"
31,2023,"$32,575","$32,716","$25,523"
32,2023,"$31,436","$31,577","$24,683"
33,2023,"$36,004","$36,173","$27,678"
34,2024,"$39,841","$40,035","$30,458"
35,2024,"$43,668","$43,890","$31,445"
36,2024,"$44,822","$45,057","$33,382"
37,2024,"$47,873","$48,134","$34,286"
38,2025,"$43,088","$43,330","$32,616"
39,2025,"$51,176","$51,471","$36,233"
40,2025,"$56,289","$56,622","$39,210"

**📊 Average Annual Returns**

                                          Unnamed: 0  1 Year 5 Years 10 Years
0                         ETF Shares Net Asset Value  25.58%  17.35%   18.86%
1                            ETF Shares Market Price  25.54%  17.35%   18.87%
2                      CRSP US Mega Cap Growth Index  25.67%  17.43%   18.93%
3  Dow Jones U.S. Total Stock Market Float Adjust...  17.46%  15.69%   14.64%

**🏗️ Sector Allocation**

                                  0      1
0                   Basic Materials   0.4%
1            Consumer Discretionary  16.1%
2                  Consumer Staples   0.3%
3                        Financials   1.4%
4                       Health Care   4.7%
5                       Industrials   6.1%
6                       Real Estate   1.4%
7                        Technology  68.3%
8                Telecommunications   1.2%
9  Other Assets and Liabilities—Net   0.1%

================================================================================

### 🏦 Vanguard Mega Cap Growth Index Fund

🆔 Context ID:      From2024-10-01to2025-09-30_C000055215Member
🎫 Ticker:          VMGAX
🏷️ Share Class:     ShareClassType.INSTITUTIONAL
📅 Report Date:     2025-09-30
🏛️ Sec Exchange:    N/A
📋 Registrant:     Vanguard World Fund

--- 💰 Costs & Financials ---
Net Assets          : 31303000000.0
Expense Ratio       : 0.06
Turnover Rate       : 14.0
Costs per $10k      : 7
Advisory Fees       : 551000.0
Number of Holdings  : 69

📝 Commentary: "How did the Fund perform during the reporting period? For the 12 months ended September 30, 2025, the Fund performed in line with its benchmark.Optimism in the U.S. about deregulation, tax cuts, and artificial intelligence was occasionally tempered b..."

**📈 Performance History**

,Unnamed: 0,Institutional Shares,CRSP US Mega Cap Growth Index,Dow Jones U.S. Total Stock Market Float Adjusted Index
0,2015,"$5,000,000","$5,000,000","$5,000,000"
1,2015,"$5,361,309","$5,362,157","$5,313,524"
2,2016,"$5,381,899","$5,383,728","$5,362,100"
3,2016,"$5,423,973","$5,426,169","$5,502,285"
4,2016,"$5,709,175","$5,711,806","$5,746,309"
5,2016,"$5,705,320","$5,707,881","$5,984,058"
6,2017,"$6,289,432","$6,293,802","$6,330,695"
7,2017,"$6,596,694","$6,602,524","$6,521,112"
8,2017,"$6,931,621","$6,938,243","$6,818,939"
9,2017,"$7,387,780","$7,395,650","$7,250,423"
10,2018,"$7,472,731","$7,481,655","$7,206,584"
11,2018,"$7,951,386","$7,961,332","$7,485,722"
12,2018,"$8,591,029","$8,602,174","$8,017,716"
13,2018,"$7,176,961","$7,184,934","$6,866,408"
14,2019,"$8,351,842","$8,362,682","$7,830,487"
15,2019,"$8,725,540","$8,738,266","$8,150,619"
16,2019,"$8,937,169","$8,951,607","$8,243,262"
17,2019,"$9,871,203","$9,887,931","$8,988,125"
18,2020,"$8,634,939","$8,651,139","$7,104,142"
19,2020,"$11,122,498","$11,143,745","$8,673,353"
20,2020,"$12,654,640","$12,680,507","$9,460,426"
21,2020,"$13,921,487","$13,950,931","$10,856,817"
22,2021,"$14,137,774","$14,169,801","$11,556,938"
23,2021,"$15,835,906","$15,873,998","$12,514,764"
24,2021,"$16,096,666","$16,137,498","$12,499,945"
25,2021,"$17,889,914","$17,937,437","$13,642,408"
26,2022,"$16,134,796","$16,178,994","$12,905,795"
27,2022,"$12,498,410","$12,534,078","$10,732,890"
28,2022,"$12,008,905","$12,044,567","$10,243,119"
29,2022,"$11,888,012","$11,925,164","$10,978,170"
30,2023,"$14,147,281","$14,193,368","$11,773,445"
31,2023,"$16,302,669","$16,358,113","$12,761,529"
32,2023,"$15,732,687","$15,788,441","$12,341,717"
33,2023,"$18,020,071","$18,086,614","$13,838,962"
34,2024,"$19,940,855","$20,017,646","$15,229,186"
35,2024,"$21,857,176","$21,944,967","$15,722,506"
36,2024,"$22,434,626","$22,528,464","$16,690,959"
37,2024,"$23,962,560","$24,067,211","$17,143,018"
38,2025,"$21,568,425","$21,664,752","$16,308,243"
39,2025,"$25,616,969","$25,735,432","$18,116,466"
40,2025,"$28,176,738","$28,311,109","$19,605,119"

**📊 Average Annual Returns**

                                          Unnamed: 0  1 Year 5 Years 10 Years
0                               Institutional Shares  25.59%  17.36%   18.88%
1                      CRSP US Mega Cap Growth Index  25.67%  17.43%   18.93%
2  Dow Jones U.S. Total Stock Market Float Adjust...  17.46%  15.69%   14.64%

**🏗️ Sector Allocation**

                                  0      1
0                   Basic Materials   0.4%
1            Consumer Discretionary  16.1%
2                  Consumer Staples   0.3%
3                        Financials   1.4%
4                       Health Care   4.7%
5                       Industrials   6.1%
6                       Real Estate   1.4%
7                        Technology  68.3%
8                Telecommunications   1.2%
9  Other Assets and Liabilities—Net   0.1%

================================================================================

### Vanguard Specialized Funds

In [5]:
from src.simple_rag.extraction.filing_retriever import FilingRetriever
from src.simple_rag.utils.fund_utils import print_fund_info
retriever = FilingRetriever(email_identity="luis.alvarez.conde@alumnos.upm.es")
result = retriever.get_ncsr_filings("VDIGX", vanguard=True, verbose=True)  


funds.extend(result.funds)                          
  
# Run Verifier
warnings = FilingRetriever.verify_ncsr_data(result)
if not warnings:
    print("All parsed data looks perfectly clean! ✅")
else:
    print("Data issues found:")
    for ticker, issues in warnings.items():
        print(f"  {ticker}: {issues}")   
print(f"{len(result.funds)} funds from {result.filings_processed} filings")
print_fund_info(result.funds[:1])

Identity of the Edgar REST client set to [luis.alvarez.conde@alumnos.upm.es]
[VDIGX] Processing N-CSR filing: 2026-01-31

Processing filing:  2026-01-31

Processing: Vanguard Real Estate Index Fund
Processing: Vanguard Real Estate Index Fund
Processing: Vanguard Real Estate Index Fund
Processing: Vanguard Real Estate Index Fund
Processing: Vanguard Global Capital Cycles Fund
Processing: Vanguard Global ESG Select Stock Fund
Processing: Vanguard Global ESG Select Stock Fund
[VDIGX] Filing 2026-03-27: 7 funds extracted
[VDIGX] Processing N-CSR filing: 2026-01-31

Processing: Vanguard Real Estate Index Fund Investor Shares
Processing: Vanguard Real Estate Index Fund ETF Shares
Processing: Vanguard Real Estate Index Fund Admiral Shares
Processing: Vanguard Real Estate Index Fund Institutional Shares
Processing: Vanguard Global Capital Cycles Fund Investor Shares
Processing: Vanguard Global ESG Select Stock Fund Investor Shares
Processing: Vanguard Global ESG Select Stock Fund Admiral Shares
Processing filing:  2026-01-31

Processing: Vanguard Dividend Growth Fund
Processing: Vanguard Energy Fund
Processing: Vanguard Energy Fund
Processing: Vanguard Health Care Fund
Processing: Vanguard Health Care Fund
Processing: Vanguard Dividend Appreciation Index Fund
Processing: Vanguard Dividend Appreciation Index Fund
[VDIGX] Filing 2026-03-27: 7 funds extracted
[VDIGX] Processing N-CSR filing: 2025-01-31

Processing: Vanguard Dividend Growth Fund Investor Shares
Processing: Vanguard Energy Fund Investor Shares
Processing: Vanguard Energy Fund Admiral Shares
Processing: Vanguard Health Care Fund Investor Shares
Processing: Vanguard Health Care Fund Admiral Shares
Processing: Vanguard Dividend Appreciation Index Fund ETF Shares
Processing: Vanguard Dividend Appreciation Index Fund Admiral Shares
Processing filing:  2025-01-31

Processing: Vanguard Dividend Growth Fund
Processing: Vanguard Energy Fund
Processing: Vanguard Energy Fund
Processing: Vanguard Health Care Fund
Processing: Vanguard Health Care Fund
Processing: Vanguard Dividend Appreciation Index Fund
Processing: Vanguard Dividend Appreciation Index Fund
[VDIGX] Duplicate fund ticker 'VDIGX' — stopping iteration
[VDIGX] N-CSR complete: 14 funds from 2 filing(s)
[VDIGX] Enrichment complete

Processing: Vanguard Dividend Growth Fund Investor Shares
Fund already exists:  VDIGX aborting
Number of funds with performance chart: 7
Funds extracted (14):  {'VGSIX', 'VDIGX', 'VDADX', 'VGENX', 'VNQ', 'VGSNX', 'VGSLX', 'VESGX', 'VIG', 'VGHAX', 'VGPMX', 'VGHCX', 'VGELX', 'VEIGX'}
All parsed data looks perfectly clean! ✅
14 funds from 2 filings
Showing information of 1 funds

### 🏦 Vanguard Real Estate Index Fund

🆔 Context ID:      FY2026_C000008010Member
🎫 Ticker:          VGSIX
🏷️ Share Class:     ShareClassType.INVESTOR
📅 Report Date:     2026-01-31
🏛️ Sec Exchange:    N/A
📋 Registrant:     Vanguard Specialized Funds

--- 💰 Costs & Financials ---
Net Assets          : 65742000000.0
Expense Ratio       : 0.27
Turnover Rate       : 7.0
Costs per $10k      : 28
Advisory Fees       : 1208000.0
Number of Holdings  : 159

📝 Commentary: "How did the Fund perform during the reporting period?    For the 12 months ended January 31, 2026, the Fund performed in line with its benchmark.   The first part of the period was marked by volatility in the financial markets amid fears that U.S. ta..."

**📊 Average Annual Returns**

,0,1,2,3
0,Average Annual Total Returns,NaN,NaN,NaN
1,NaN,1 Year,5 Years,10 Years
2,Investor Shares,4.04%,5.03%,5.63%
3,Real Estate Spliced Index,4.31%,5.31%,5.89%
4,Dow Jones U.S. Total Stock Market Float Adjust...,15.34%,13.50%,15.06%

**🏗️ Sector Allocation**

,0,1
0,Portfolio Composition % of Net Assets (as of J...,NaN
1,Data Center REITs,7.8%
2,Health Care REITs,13.1%
3,Industrial REITs,9.8%
4,Multi-Family Residential REITs,6.3%
5,Other Specialized REITs,5.4%
6,Real Estate Services,7.2%
7,Retail REITs,12.0%
8,Self-Storage REITs,4.8%
9,Single-Family Residential REITs,3.1%
10,Telecom Tower REITs,8.0%
11,Vanguard Real Estate II Index Fund1,14.5%
12,Other Assets and Liabilities—Net,8.0%
13,"This table reflects the Fund’s investments, in...","This table reflects the Fund’s investments, in..."

================================================================================

### Vanguard Whitehall Funds

In [6]:
from src.simple_rag.extraction.filing_retriever import FilingRetriever
from src.simple_rag.utils.fund_utils import print_fund_info
import gc, pickle
from pathlib import Path

# Add a checkpoint to save the vanguard funds extracted
CHECKPOINT_DIR = Path("edgar_cache/vanguard")
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
checkpoint_path = CHECKPOINT_DIR / f"vanguard.pkl"
 

retriever = FilingRetriever(email_identity="luis.alvarez.conde@alumnos.upm.es")
result = retriever.get_ncsr_filings("VMGRX", vanguard=True, verbose=True) 
extracted = result.funds

# Run Verifier
warnings = FilingRetriever.verify_ncsr_data(result)
if not warnings:
    print("All parsed data looks perfectly clean! ✅")
else:
    print("Data issues found:")
    for ticker, issues in warnings.items():
        print(f"  {ticker}: {issues}")   
verified = [f for f in result.funds if f.ticker not in warnings]
print(f"{len(verified)} clean funds from {result.filings_processed} filings")

print_fund_info(verified[:1])

funds.extend(extracted) 
with open(checkpoint_path, "wb") as f:
    pickle.dump(funds, f)

print(f"Saved {len(funds)} funds to {checkpoint_path}")

del result, retriever, verified
gc.collect()

Identity of the Edgar REST client set to [luis.alvarez.conde@alumnos.upm.es]
[VMGRX] Processing N-CSR filing: 2025-10-31

Processing filing:  2025-10-31

Processing: Vanguard Mid-Cap Growth Fund
Processing: Vanguard Selected Value Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Global Minimum Volatility Fund
Processing: Vanguard Global Minimum Volatility Fund
Processing: Vanguard International Dividend Appreciation Index Fund
Processing: Vanguard International Dividend Appreciation Index Fund
Processing: Vanguard International High Dividend Yield Index Fund
Processing: Vanguard International High Dividend Yield Index Fund
Processing: Vanguard International Dividend Growth Fund
[VMGRX] Filing 2025-12-30: 12 funds extracted
[VMGRX] Processing N-CSR filing: 2025-10-31

Processing: Vanguard Mid-Cap Growth Fund Investor Shares
Processing: Vanguard Selected Value Fund Investor Shares
Processing: Vanguard Emerging Markets Government Bond Index Fund ETF Shares
Processing: Vanguard Emerging Markets Government Bond Index Fund Admiral Shares
Processing: Vanguard Emerging Markets Government Bond Index Fund Institutional Shares
Processing: Vanguard Global Minimum Volatility Fund Investor Shares
Processing: Vanguard Global Minimum Volatility Fund Admiral Shares
Processing: Vanguard International Dividend Appreciation Index Fund ETF Shares
Processing: Vanguard International Dividend Appreciation Index Fund Admiral Shares
Processing: Vanguard International High Dividend Yield Index Fund ETF Shares
Processing: Vanguard International High Dividend Yield Index Fund Admiral Shares
Processing: Vanguard International Dividend Growth Fund Investor Shares
Processing filing:  2025-10-31

Processing: Vanguard Advice Select International Growth Fund
Processing: Vanguard Advice Select Dividend Growth Fund
Processing: Vanguard Advice Select Global Value Fund
Processing: Vanguard International Explorer™ Fund
Processing: Vanguard High Dividend Yield Index Fund
Processing: Vanguard High Dividend Yield Index Fund
[VMGRX] Filing 2025-12-30: 6 funds extracted
[VMGRX] Processing N-CSR filing: 2024-10-31

Processing: Vanguard Advice Select International Growth Fund Admiral Shares
Processing: Vanguard Advice Select Dividend Growth Fund Admiral Shares
Processing: Vanguard Advice Select Global Value Fund Admiral Shares
Processing: Vanguard International Explorer™ Fund Investor Shares
Processing: Vanguard High Dividend Yield Index Fund ETF Shares
Processing: Vanguard High Dividend Yield Index Fund Admiral Shares
Processing filing:  2024-10-31

Processing: Vanguard Mid-Cap Growth Fund
Processing: Vanguard Selected Value Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Emerging Markets Government Bond Index Fund
Processing: Vanguard Global Minimum Volatility Fund
Processing: Vanguard Global Minimum Volatility Fund
Processing: Vanguard International Dividend Appreciation Index Fund
Processing: Vanguard International Dividend Appreciation Index Fund
Processing: Vanguard International High Dividend Yield Index Fund
Processing: Vanguard International High Dividend Yield Index Fund
Processing: Vanguard International Dividend Growth Fund
[VMGRX] Duplicate fund ticker 'VMGRX' — stopping iteration
[VMGRX] N-CSR complete: 18 funds from 2 filing(s)
[VMGRX] Enrichment complete

Processing: Vanguard Mid-Cap Growth Fund Investor Shares
Fund already exists:  VMGRX aborting
Number of funds with performance chart: 12
Funds extracted (18):  {'VMNVX', 'VIHAX', 'VIDGX', 'VGAVX', 'VMGRX', 'VINEX', 'VIGI', 'VADGX', 'VASVX', 'VIAAX', 'VAIGX', 'VWOB', 'VMVFX', 'VYM', 'VGIVX', 'VHYAX', 'VYMI', 'VAGVX'}
All parsed data looks perfectly clean! ✅
18 clean funds from 2 filings
Showing information of 1 funds

### 🏦 Vanguard Mid-Cap Growth Fund

🆔 Context ID:      From2024-11-01to2025-10-31_C000012166Member
🎫 Ticker:          VMGRX
🏷️ Share Class:     ShareClassType.INVESTOR
📅 Report Date:     2025-10-31
🏛️ Sec Exchange:    N/A
📋 Registrant:     Vanguard Whitehall Funds

--- 💰 Costs & Financials ---
Net Assets          : 3116000000.0
Expense Ratio       : 0.32
Turnover Rate       : 128.0
Costs per $10k      : 34
Advisory Fees       : 3837000.0
Number of Holdings  : 138

📝 Commentary: "How did the Fund perform during the reporting period? For the 12 months ended October 31, 2025, the Fund underperformed its benchmark. Optimism in the U.S. about the prospect of tax cuts, robust corporate earnings, and artificial intelligence was occ..."

**📈 Performance History**

,Unnamed: 0,Investor Shares,Russell Midcap Growth Index,Dow Jones U.S. Total Stock Market Float Adjusted Index
0,2015,"$10,000","$10,000","$10,000"
1,2016,"$8,869","$9,054","$9,292"
2,2016,"$9,455","$9,846","$10,003"
3,2016,"$9,746","$10,502","$10,609"
4,2016,"$9,451","$10,040","$10,421"
5,2017,"$10,056","$10,864","$11,311"
6,2017,"$10,563","$11,405","$11,860"
7,2017,"$10,900","$11,907","$12,320"
8,2017,"$11,595","$12,675","$12,917"
9,2018,"$12,674","$13,915","$14,157"
10,2018,"$12,475","$13,329","$13,410"
11,2018,"$13,280","$14,179","$14,344"
12,2018,"$12,710","$13,454","$13,765"
13,2019,"$13,028","$13,985","$13,828"
14,2019,"$14,594","$15,680","$15,097"
15,2019,"$14,930","$16,185","$15,334"
16,2019,"$14,434","$16,001","$15,608"
17,2020,"$15,422","$17,152","$16,645"
18,2020,"$13,782","$15,716","$14,918"
19,2020,"$16,788","$19,114","$16,990"
20,2020,"$17,079","$19,382","$17,167"
21,2021,"$20,035","$22,964","$20,065"
22,2021,"$21,870","$24,198","$22,528"
23,2021,"$22,629","$25,709","$23,604"
24,2021,"$23,515","$27,024","$24,733"
25,2022,"$19,568","$22,622","$23,776"
26,2022,"$17,256","$20,149","$21,771"
27,2022,"$16,925","$20,114","$21,767"
28,2022,"$15,939","$19,204","$20,542"
29,2023,"$17,169","$20,694","$21,774"
30,2023,"$16,778","$20,471","$22,049"
31,2023,"$18,946","$22,735","$24,514"
32,2023,"$16,097","$19,847","$22,267"
33,2024,"$19,321","$23,827","$25,943"
34,2024,"$20,071","$24,708","$26,992"
35,2024,"$20,839","$25,542","$29,687"
36,2024,"$21,856","$27,522","$30,727"
37,2025,"$24,269","$31,118","$32,760"
38,2025,"$21,009","$28,081","$30,030"
39,2025,"$24,549","$32,766","$34,357"
40,2025,"$25,084","$32,914","$37,150"

**📊 Average Annual Returns**

                                          Unnamed: 0  1 Year 5 Years 10 Years
0                                    Investor Shares  14.77%   7.99%    9.63%
1                        Russell Midcap Growth Index  19.59%  11.17%   12.65%
2  Dow Jones U.S. Total Stock Market Float Adjust...  20.90%  16.69%   14.02%

**🏗️ Sector Allocation**

                                   0      1
0             Communication Services  10.5%
1             Consumer Discretionary  17.9%
2                   Consumer Staples   2.0%
3                             Energy   2.4%
4                         Financials   6.4%
5                        Health Care  11.6%
6                        Industrials  22.3%
7             Information Technology  21.3%
8                          Materials   0.7%
9                        Real Estate   0.6%
10                         Utilities   2.7%
11  Other Assets and Liabilities—Net   1.6%

================================================================================

Saved 124 funds to edgar_cache/vanguard/vanguard.pkl

317314

### Method to try the N-CSR parser with a specific CIK

In [ ]:
# ── NCSR parsing + series_id verification ──────────────────────────────────
from src.simple_rag.extraction.filing_retriever import FilingRetriever

EMAIL = "luis.alvarez.conde@alumnos.upm.es"          # required by SEC fair-use policy
CIK   = "0000036405"               # Vanguard Group (change to any CIK)

retriever = FilingRetriever(email_identity=EMAIL)

# Parse one filing (max_filings=1 keeps it fast)
result = retriever.get_ncsr_by_cik(
    cik=CIK,
    max_filings=1,
    vanguard=True,   # set False for non-Vanguard filers
    verbose=True,
)

print(f"\nFilings processed : {result.filings_processed}")
print(f"Funds extracted   : {len(result.funds)}")